/* 
 CREATE TABLE "HR"."PERSON"
  (
    "NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "COUNTRY" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "ID"  NUMBER CONSTRAINT "PERSON_ID_NN" NOT NULL ENABLE,
    CONSTRAINT "PERSON_ID_PK" PRIMARY KEY ("ID")
  )
*/
  
drop table TESTSCHEMA.PERSON_INFO;

CREATE TABLE TESTSCHEMA.PERSON_INFO ( 
 id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
 NAME VARCHAR(30) NOT NULL,
 COUNTRY VARCHAR(30) NOT NULL,
 CONSTRAINT pk_personinfo_id PRIMARY KEY (id)
);