/*All User's are stored in APP_USER table*/
create table APP_USER
( ID NUMBER NOT NULL PRIMARY KEY,
  SSO_ID VARCHAR2(30 BYTE) NOT NULL UNIQUE,
  PASSWORD VARCHAR2(100 BYTE) NOT NULL,
  FIRST_NAME VARCHAR2(30 BYTE) NOT NULL,
  LAST_NAME VARCHAR2(30 BYTE) NOT NULL,
  EMAIL VARCHAR2(30 BYTE) NOT NULL,
  STATE VARCHAR2(30 BYTE) NOT NULL
);

CREATE SEQUENCE app_user_seq START WITH 1;

create or replace
TRIGGER increment_id
  BEFORE INSERT ON APP_USER
  FOR EACH ROW
BEGIN
  SELECT app_user_seq.NEXTVAL
  INTO :new.ID
  FROM dual;
END increment_id;

  
/* USER_PROFILE table contains all possible roles */
create table USER_PROFILE (
  ID NUMBER NOT NULL PRIMARY KEY,
  TYPE VARCHAR2(30 BYTE) NOT NULL UNIQUE
);

CREATE SEQUENCE user_profile_seq START WITH 1;

create or replace
TRIGGER increment_UP_id
  BEFORE INSERT ON USER_PROFILE
  FOR EACH ROW
BEGIN
  SELECT user_profile_seq.NEXTVAL
  INTO :new.ID
  FROM dual;
END increment_UP_id;


/* JOIN TABLE for MANY-TO-MANY relationship*/ 
CREATE TABLE APP_USER_USER_PROFILE (
  USER_ID NUMBER NOT NULL,
  USER_PROFILE_ID NUMBER NOT NULL,
  Constraint APP_USER_USER_PROFILE_PK PRIMARY KEY (USER_ID, USER_PROFILE_ID),
  CONSTRAINT FK_APP_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID),
  CONSTRAINT FK_USER_PROFILE FOREIGN KEY (USER_PROFILE_ID) REFERENCES USER_PROFILE (ID)
);
 
/* Populate USER_PROFILE Table */
INSERT INTO USER_PROFILE(TYPE) VALUES ('USER');
INSERT INTO USER_PROFILE(TYPE) VALUES ('ADMIN'); 
INSERT INTO USER_PROFILE(TYPE) VALUES ('DBA');
 
/* Populate APP_USER Table */
INSERT INTO APP_USER (SSO_ID,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL,STATE) 
VALUES('bill','abc123', 'Bill','Watcher','bill@xyz.com', 'Active');
INSERT INTO APP_USER (SSO_ID,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL,STATE) 
VALUES('danny','abc124', 'Danny','Theys','danny@xyz.com', 'Active');
INSERT INTO APP_USER (SSO_ID,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL,STATE) 
VALUES('sam','abc125', 'Sam','Smith','samy@xyz.com', 'Active');
INSERT INTO APP_USER (SSO_ID,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL,STATE) 
VALUES('nicole','abc126', 'Nicole','warner','nicloe@xyz.com', 'Active');
INSERT INTO APP_USER (SSO_ID,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL,STATE) 
VALUES('kenny','abc127', 'Kenny','Roger','kenny@xyz.com', 'Active');
 
/* Populate JOIN Table */
INSERT INTO APP_USER_USER_PROFILE (USER_ID,USER_PROFILE_ID)
SELECT usera.ID,profile.ID from APP_USER usera,USER_PROFILE profile
where usera.SSO_ID='bill' and profile.TYPE='USER';

INSERT INTO APP_USER_USER_PROFILE (USER_ID,USER_PROFILE_ID)
SELECT usera.ID,profile.ID from APP_USER usera,USER_PROFILE profile
where usera.SSO_ID='danny' and profile.TYPE='USER';

INSERT INTO APP_USER_USER_PROFILE (USER_ID,USER_PROFILE_ID)
SELECT usera.ID,profile.ID from APP_USER usera,USER_PROFILE profile
where usera.SSO_ID='sam' and profile.TYPE='ADMIN';

INSERT INTO APP_USER_USER_PROFILE (USER_ID,USER_PROFILE_ID)
SELECT usera.ID,profile.ID from APP_USER usera,USER_PROFILE profile
where usera.SSO_ID='nicole' and profile.TYPE='DBA';

INSERT INTO APP_USER_USER_PROFILE (USER_ID,USER_PROFILE_ID)
SELECT usera.ID,profile.ID from APP_USER usera,USER_PROFILE profile
where usera.SSO_ID='kenny' and profile.TYPE='ADMIN';
 
INSERT INTO APP_USER_USER_PROFILE (USER_ID,USER_PROFILE_ID)
SELECT usera.ID,profile.ID from APP_USER usera,USER_PROFILE profile
where usera.SSO_ID='kenny' and profile.TYPE='DBA';